services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./app:/app

  spark-worker-1:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
      - ./app:/app

  streamlit-app:
    build: .
    depends_on:
      - spark-master
      - spark-worker-1
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
      - ./app:/app
